# -*- coding: utf-8 -*-
"""capstone_R.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLYKdaCYaSsMcYY_6ytxarkIIoype0Cf

# **Titre : Analyse sous R de la production mensuelle d’électricité en Tunisie (2005–2024)**

---


*   Ines elouaer

**1) Introduction**
* Cette étude analyse l’évolution mensuelle de la production d’électricité en Tunisie entre 2005 et 2024, ventilée par type de producteur (STEG, IPP, auto-producteurs et solaire). L’objectif est de décrire les tendances, la saisonnalité et les différences entre producteurs, ainsi que de proposer un modèle statistique simple et interprétable permettant d’expliquer la production totale.


> 1.1 Objectifs

Les objectifs de l’analyse sont :

* Décrire la production totale et son évolution dans le temps

* Comparer les producteurs (niveaux, dispersion, apparition du solaire/auto)

* Mettre en évidence la saisonnalité mensuelle

* Tester si la production STEG diffère significativement de celle des IPP

* Modéliser la production totale et choisir un modèle pertinent

**2) Import + inspection initiale**
"""

system("git clone https://github.com/ines-elouaer/capstone_R_elouaer_ines.git")
setwd("capstone_R_elouaer_ines")

system("ls")
system("ls data")

library(readr)
library(dplyr)
library(ggplot2)
library(lubridate)

data <- read.csv(
  "data/opendataproductionmensuelleelectriciteparproducteurs.csv",
  sep = ";",
  stringsAsFactors = FALSE
)

"""**2.1. Compréhension initiale des données**"""

str(data)
summary(data)
head(data, 10)

"""**3) Nettoyage : renommage des variables**

*   Les noms de colonnes sont renommés pour améliorer la lisibilité du code et faciliter l’analyse. Cette étape réduit les erreurs et rend les graphiques/modèles plus clairs.
"""

data <- data %>%
  rename(
    date = Date,
    steg = Production.STEG..en.GWh,
    ipp = Production.IPP.en.GWh,
    solaire = IPP.Solaire,
    auto = Production.Auto.producteurs..en.GWh,
    total = Production.totale..GWh.
  )

str(data)
summary(data)

"""**3.2 Nettoyage : conversion des dates (formats mixtes FR)**

*   La variable date est fournie sous plusieurs formats (ex. m / Y et janv-22). Une conversion en véritable format date est nécessaire pour réaliser des séries temporelles correctes et des analyses saisonnières.
"""

library(stringr)

to_date_fr <- function(x){
  x <- str_trim(x)

  # Cas 1 : "1 / 2005" (mois / année)
  # on enlève les espaces et on parse
  is_num <- str_detect(x, "^\\d+\\s*/\\s*\\d{4}$")

  out <- rep(as.Date(NA), length(x))

  # Parser "m / Y"
  out[is_num] <- my(str_replace_all(x[is_num], "\\s+", ""))  # my = month-year

  # Cas 2 : "janv-22", "févr-22", etc.
  # On remplace mois FR -> EN abréviations reconnues (Jan, Feb, Mar...)
  m <- x[!is_num]

  # Corriger encodage fréquent: "f�vr", "d�c", "ao�t" (caractères cassés)
  m <- str_replace_all(m, c("f�vr"="févr","d�c"="déc","ao�t"="août"))

  # map mois FR -> EN
  m2 <- str_replace_all(m, c(
    "janv"="Jan", "févr"="Feb", "fevr"="Feb", "mars"="Mar", "avr"="Apr",
    "mai"="May", "juin"="Jun", "juil"="Jul", "août"="Aug", "aout"="Aug",
    "sept"="Sep", "oct"="Oct", "nov"="Nov", "déc"="Dec", "dec"="Dec"
  ))

  # parser "Mon-YY"
  out[!is_num] <- my(m2)

  out
}

data$date <- to_date_fr(data$date)

head(data$date, 15)
tail(data$date, 15)
range(data$date, na.rm = TRUE)

"""**4) Contrôle qualité : NA + doublons**

*   Gestion des valeurs manquantes (NA) : La vérification des valeurs manquantes montre que les NA concernent principalement solaire et auto, disponibles uniquement sur les années récentes. Ces NA ne sont pas supprimés ni remplacés afin de préserver la cohérence temporelle. Pour les statistiques descriptives et certaines visualisations, les calculs sont réalisés avec na.rm=TRUE. Pour les analyses dédiées à la production solaire ou aux auto-producteurs, un filtrage ciblé (filter(!is.na(...))) est appliqué afin de se limiter à la période où ces variables existent.
"""

colSums(is.na(data))
summary(is.na(data))

sum(duplicated(data))
data %>% filter(duplicated(.))

"""**5) Transformation (Pivot wide -> long)**

*   La transformation en format long (tidy data) permet de regrouper les producteurs dans une seule colonne (producteur) et leurs valeurs dans une autre (production), ce qui simplifie les tableaux de synthèse et les visualisations comparatives.
"""

library(tidyr)

data_long <- data %>%
  pivot_longer(
    cols = c(steg, ipp, solaire, auto),
    names_to = "producteur",
    values_to = "production"
  )

str(data_long)
summary(data_long)

"""**6) Normalisation**
* La normalisation n’est pas nécessaire pour l’analyse en GWh, mais une standardisation (z-score) peut être utilisée pour comparer visuellement les dynamiques sur une même échelle.
"""

data_scaled <- data %>%
  mutate(
    steg_z  = as.numeric(scale(steg)),
    ipp_z   = as.numeric(scale(ipp)),
    total_z = as.numeric(scale(total))
  )

data_scaled_long <- data_scaled %>%
  select(date, steg_z, ipp_z, total_z) %>%
  pivot_longer(-date, names_to = "serie", values_to = "z")

ggplot(data_scaled_long, aes(x = date, y = z, color = serie)) +
  geom_line() +
  theme_minimal() +
  labs(
    title = "Comparaison des séries standardisées (z-score)",
    x = "Date",
    y = "Valeur standardisée"
  )

"""**7) Statistiques descriptives (tableaux de synthèse)**
* Nous calculons des statistiques descriptives par producteur. Le nombre d’observations n montre que solaire/auto sont disponibles seulement sur les années récentes.
"""

tab_stats <- data_long %>%
  group_by(producteur) %>%
  summarise(
    n = sum(!is.na(production)),
    moyenne = mean(production, na.rm = TRUE),
    mediane = median(production, na.rm = TRUE),
    ecart_type = sd(production, na.rm = TRUE),
    min = min(production, na.rm = TRUE),
    max = max(production, na.rm = TRUE)
  )

tab_stats

"""**8) Analyse exploratoire (EDA) : graphiques**

*  L’analyse exploratoire (EDA) permet d’identifier visuellement la tendance globale, la saisonnalité et les différences de niveaux entre producteurs avant de passer aux tests statistiques et aux modèles.

Figure 1 — production totale (tendance + saisonnalité):

---
Cette figure représente la production totale d’électricité chaque mois entre 2005 et 2024. La courbe noire montre les variations mensuelles, avec des pics qui reviennent régulièrement, ce qui indique une saisonnalité. La courbe bleue (lissée) résume la tendance globale : la production augmente au fil du temps, même si certains mois restent plus élevés que d’autres.
"""

library(dplyr)
library(lubridate)
library(ggplot2)

data_plot <- data %>%
  arrange(date) %>%
  mutate(
    year  = year(date),
    month = month(date)
  )

ggplot(data_plot, aes(x = date, y = total)) +
  geom_line(linewidth = 0.7, alpha = 0.8) +
  geom_smooth(method = "loess", span = 0.15, se = FALSE, linewidth = 1.1) +
  labs(
    title = "Production totale mensuelle d’électricité (2005–2024)",
    subtitle = "Les pics répétés chaque année montrent la saisonnalité ; la courbe lissée montre la tendance",
    x = "Date",
    y = "Production (GWh)"
  ) +
  theme_minimal()

"""2.  Figure 2 – Production mensuelle d’électricité par type de producteur

---
Ce graphique illustre l’évolution mensuelle de la production d’électricité en Tunisie selon le type de producteur. La STEG reste le principal producteur avec une tendance croissante et une forte saisonnalité. Les IPP jouent un rôle complémentaire et plus stable, tandis que la production solaire et celle des auto-producteurs apparaissent récemment et demeurent encore marginales.

"""

# 7.2 Série temporelle par producteur (NA ignorés automatiquement)
ggplot(data_long, aes(x = date, y = production, color = producteur)) +
  geom_line() +
  labs(
    title = "Production mensuelle d’électricité par type de producteur",
    x = "Date", y = "GWh"
  ) +
  theme_minimal()

"""3. Figure 3 – Boxplot : Distribution de la production par producteur

---

Ce boxplot permet de comparer rapidement les niveaux et la variabilité de la production selon le type de producteur. Il montre que la STEG produit nettement plus que les autres et présente une forte dispersion (variations mensuelles importantes). Les points extrêmes correspondent à des mois de production très élevée. Les IPP ont une production plus faible et plus stable, tandis que le solaire et les auto-producteurs restent encore très marginaux.
"""

# 7.3 Boxplot par producteur (comparaison des distributions)
ggplot(data_long, aes(x = producteur, y = production, fill = producteur)) +
  geom_boxplot(na.rm = TRUE) +
  labs(title = "Distribution de la production par producteur", x = "", y = "GWh") +
  theme_minimal() +
  theme(legend.position = "none")

"""**9) Préparer les données (steg & ipp sans NA)**"""

df_test <- data %>% select(steg, ipp) %>% na.omit()

"""**9.1 Test de normalité (Shapiro) sur chaque variable**

* Nous utilisons un test t apparié car les deux séries sont observées sur les mêmes mois : Les tests de normalité montrent que les productions mensuelles de la STEG et des IPP ne suivent pas une distribution normale. Cependant, comme le nombre d’observations est élevé, le test t apparié reste valable. Les résultats indiquent une différence très significative entre les deux producteurs, la STEG produisant en moyenne environ 936 GWh de plus par mois que les IPP.
"""

# Normalité (indicatif)
shapiro.test(df_test$steg)
shapiro.test(df_test$ipp)

# Test t apparié
t_test_res <- t.test(df_test$steg, df_test$ipp, paired = TRUE)
t_test_res

"""# **10) régression**
* Nous comparons plusieurs modèles :
(1) tendance seule, (2) tendance + saisonnalité.
Le modèle temps+saison est retenu car il est interprétable et explique mieux la variabilité.
"""

data <- data %>%
  arrange(date) %>%
  mutate(
    time = row_number(),
    month = month(date)
  )

m1 <- lm(total ~ time, data = data)
m2 <- lm(total ~ time + factor(month), data = data)

summary(m1)
summary(m2)

data.frame(
  modele = c("Temps", "Temps + Saison"),
  R2 = c(summary(m1)$r.squared, summary(m2)$r.squared),
  R2_ajuste = c(summary(m1)$adj.r.squared, summary(m2)$adj.r.squared)
)

"""**11) Diagnostic du modèle retenu (m2)**
* Diagnostic : on vérifie que les résidus sont globalement centrés autour de 0 et qu’il n’y a pas de structure trop marquée. Une légère non-linéarité peut indiquer des effets non capturés, mais le modèle reste pertinent pour une analyse exploratoire.
"""

diag_df <- data.frame(
  fitted = fitted(m2),
  resid  = residuals(m2)
)

# Résidus vs ajustés
ggplot(diag_df, aes(x = fitted, y = resid)) +
  geom_point(alpha = 0.6) +
  geom_hline(yintercept = 0, linetype = "dashed", linewidth = 1) +
  geom_smooth(method = "loess", se = FALSE) +
  labs(
    title = "Diagnostic : Résidus vs valeurs ajustées (Temps + Saison)",
    x = "Valeurs ajustées",
    y = "Résidus"
  ) +
  theme_minimal()

# QQ-plot
qqnorm(residuals(m2), main = "QQ-plot des résidus (Temps + Saison)")
qqline(residuals(m2))

# Normalité des résidus (indicatif)
shapiro.test(residuals(m2))

data$valeur_modele <- fitted(m2)

ggplot(data, aes(x = date)) +
  geom_line(aes(y = total), color = "black") +
  geom_line(aes(y = valeur_modele), color = "red", linetype = "dashed") +
  labs(
    title = "Production réelle vs valeurs estimées par le modèle",
    x = "Date",
    y = "GWh"
  ) +
  theme_minimal()

"""# **12) Conclusion + limites + perspectives**


---
# 12.1. Conclusion
Ce projet a permis de réaliser une analyse statistique complète de la production mensuelle d’électricité en Tunisie sur la période 2005–2024. À travers un travail structuré de nettoyage, de transformation et d’exploration des données, les principales dynamiques du système électrique ont été mises en évidence.

Les résultats montrent une augmentation globale de la production au fil du temps, accompagnée d’une forte saisonnalité, avec des pics récurrents durant les mois estivaux. La STEG demeure le principal producteur d’électricité, tandis que les producteurs indépendants jouent un rôle complémentaire stable. La production solaire apparaît récemment et reste encore marginale, bien qu’en progression.

Les tests statistiques confirment une différence significative entre les niveaux de production de la STEG et des IPP. Les modèles de régression montrent que l’intégration de la saisonnalité améliore fortement la qualité d’ajustement, tandis que le modèle complet permet de capturer l’essentiel de la variabilité observée.

Ce travail s’inscrit dans une démarche d’analyse statistique exploratoire, privilégiant l’interprétation et la compréhension des données plutôt que la prédiction. Les résultats obtenus constituent une base solide pour des analyses futures plus avancées, notamment des modèles de séries temporelles ou des études intégrant des variables exogènes (demande, climat, politique énergétique).
# 12.2. Limites
Les données sont agrégées mensuellement, ce qui limite l’analyse fine des variations quotidiennes. Les valeurs manquantes du solaire/auto correspondent à des périodes d’absence de production, ce qui réduit la comparabilité sur l’ensemble de la période. Enfin, certains effets non linéaires peuvent subsister comme le suggèrent les diagnostics.
# 12.3 Perspectives
Des analyses futures pourraient intégrer d’autres variables explicatives (température, consommation, prix, politiques énergétiques) ou utiliser des modèles de séries temporelles (décomposition, ARIMA) pour prévoir la production.
"""